### ISSUE TITLE
Part 3 - Chapter 10. Redis의 백업과 장애 복구

### ISSUE THREAD

**Issue by leegwichan** [leegwichan/fastCampus_trafficHandling#20]
Unit 01. RDB를 사용한 백업
Unit 02. AOF를 사용한 백업
Unit 03. Redis의 복제
Unit 04. Redis Sentinel을 이용한 자동 장애조치

**Comment by leegwichan** [comment]
### Unit 01. RDB를 사용한 백업

- 백업 : Inmemory에 있는 Redis의 데이터를 Disk로 옮기는 과정을 의미함

#### RDB(Redis Database)를 사용한 백업
- 특정 시점의 스냅샷으로 데이터를 저장
- 재시작 시 RDB 파일이 있으면 읽어서 복구
![image](https://github.com/leegwichan/fastCampus_trafficHandling/assets/44027393/bc09505d-686c-44d0-8426-0c7b0025efea)

#### RDB 사용의 장점
- 상대적으로 작은 파일 사이즈로 백업 파일 관리가 용이 (원격 백업, 버전 관리 등)
- fork()를 이용해 백업하므로 서비스 중인 프로세스는 성능에 영향 없음
- 데이터 스냅샷 방식이므로 빠른 복구 가능

#### RDB 사용의 단점
- 스냅샷을 저장하는 시점 사이의 데이터 변경사항은 유실될 수 있다.
- fork()를 이용하기 떄문에 시간이 오래 걸릴 수 있고, CPU와 메모리 자원을 많이 소모
- 데이터 무결성이나 정합성에 대한 요구가 크지 않은 경우 사용 가능 (마지막 백업 시 에러 발생 등의 문제)

#### RDB 설정 방법
- 설정파일이 없어도 기본값으로 RDB를 활성화되어 있음
- 설정 파일 만드려면 [템플릿을 받아서 사용](https://redis.io/docs/management/config/)

#### 설정 예시
- 저장 주기 설정 (60초마다 10개 이상의 변경이 있을 경우)
```
save 60 10
```

- 스냅샷을 저장할 파일 이름 설정
```
dbfilename dump.rdb
```

- 수동으로 스냅샷 저장
```
bgsave
```

#### 참고
- Docker 컨테이너 실행 시 설정 파일 적용하기
```shell
docker run -v /my/redis.conf:/redis.conf --name my-redis redis redis-server /redis.conf
```

**Comment by leegwichan** [comment]
### Unit 02. AOF를 사용한 백업

- AOP(Append Only File)
  - 모든 쓰기 요청에 대한 로그를 저장
  - 재시작 시 AOF에 기록된 모든 동작을 재수행해서 데이터를 복구
![image](https://github.com/leegwichan/fastCampus_trafficHandling/assets/44027393/0357b3da-3ce9-44de-96a2-e6e07d500641)

- AOF의 장점
  - 모든 변경사항이 기록되므로 RDB 방식 대비 안정적으로 데이터 백업 가능
  - AOF 파일은 append-only 방식이므로 백업 파일이 손상될 위험이 적음
  - 실제 수행된 명령어가 저장되어 있으므로 사람이 보고 이해할 수 있고 수정도 가능

- AOF의 단점
  - RDB 방식보다 파일 사이즈가 커짐
  - RDB 방식 대비 백업&복구 속도가 느림

**Comment by leegwichan** [comment]
### Unit 03. Redis의 복제

#### Redis Replication (복제)
- Master가 죽었을 경우, replica 중 하나를 master로 전환해 즉시 서비스 정상화 가능
- replica은 read-only 노드로 사용 가능하므로 traffic 분산도 가능함

![image](https://github.com/leegwichan/fastCampus_trafficHandling/assets/44027393/b44a7a58-2922-49cf-9de1-2386760d4a7b)

#### 설정 방법
- Replica 노드에서만 설정을 적용해 master-replica 복제 구성 가능
- 주의 사항 : Master 노드에는 RDB나 AOF를 이용한 백업 기능 활성화가 필수 (재시작 후에 비어있는 데이터 상태가 복제되지 않도록 함)

- Replica로 동작하도록 설정
  - Master의 IP와 PORT 입력
```
replicaof 127.0.0.1 6379
```
- Replica는 read-only로 설정
```
replica-read-only
```

**Comment by leegwichan** [comment]
### Docker로 사용한 명령어

- Master 생성
```
docker run --name my-redis-master -p 5000:6379 redis
```

- Replica 생성
  - redis.conf 파일에 "replicaof 127.0.0.1 5000" 설정
  - --network host : host와 같은 연결 사용 (5000 번의 Master를 인식하기 위해서)
  - -v $(pwd)/redis.conf:/redis.conf : ":"를 기준으로 앞은 현재 PC에서의 위치, 뒤는 Docker Container 안의 위치를 의미하고 해당 파일을 Docker Container 안에 가져감
  - --name my-redis-replica : docker container 이름 설정
  - redis-server /redis.conf : redis 실행 시 redis.conf의 설정 파일을 적용함
```
docker run --network host -v $(pwd)/redis.conf:/redis.conf --name my-redis-replica redis redis-server /redis.conf
```

- Docker Container 안의  shell에 접속하는 방법
```
docker exec -it [컨테이너 이름] /bin/sh
redis-cli
```

**Comment by leegwichan** [comment]
### Unit 04. Redis Sentinel을 이용한 자동 장애조치

#### Redis Sentinel
- Redis에서 HA(high availability)를 제공하기 위한 장치
- master-replica 구조에서 master가 다운 시 replica를 master로 승격시키는 auto-failover를 수행함
- Sentinel의 기능 : 모니터링, 알림, 자동 장애 복구, 환경 설정 제공자

#### Redis Sentinal 구성도
- Sentinal 노드는 3개 이상으로 구성됨 ([Quorum](https://crystalcube.co.kr/177) 때문)
- Sentinal 들은 서로 연결되어 있음
- Sentinal 들을 Redis master와 replica를 모니터링
- Client는 Sentinal을 통해 Redis에 접근함
![image](https://github.com/leegwichan/fastCampus_trafficHandling/assets/44027393/bb405d1b-42e8-4a4e-ac6f-243d1affd0de)

#### Redis Sentinal의 특징
- SDOWN과 ODOWN의 2가지 판단이 있음
  - SDOWN : Sentinal 1대가 down으로 판단 (주관적)
  - ODOWN : 정족수가 충족되어 down으로 판단 (객관적)
- master 노드가 down된걸로 판단되기 위해서는 Sentinal 노드들이 정족수(Quorum)을 충족해야 함
- Client는 Sentinal을 통해 master의 주소를 얻어내야 함

**Comment by leegwichan** [comment]
### Docker로 사용한 명령어 (Redis Sentinel)

#### docker-compose.yml 파일
```yml
version: "3"

services: 
  my-redis-a:
    hostname: redis-master
    container_name: redis-master
    image: "bitnami/redis"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 5000:6379
  
  my-redis-b:
    hostname: redis-replicas-1
    container_name: redis-replicas-1
    image: "bitnami/redis"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 5001:6379
    depends_on:
      - my-redis-a

  redis-sentinel-1:
    container_name: sentinel1
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - 26379:26379
    depends_on:
      - my-redis-a
      - my-redis-b
  redis-sentinel-2:
    container_name: sentinel2
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - 26380:26379
    depends_on:
      - my-redis-a
      - my-redis-b
  redis-sentinel-3:
    container_name: sentinel3
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - 26381:26379
    depends_on:
      - my-redis-a
      - my-redis-b
```

**Comment by leegwichan** [comment]
### Spring에서 Sentinel 사용하는 법

- application.yml
```yml
spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379, 127.0.0.1:26380, 127.0.0.1:26381
```
